### ISSUE TITLE
Typo in 2023-05-29 issue

### ISSUE THREAD

**Issue by gagbo** [phaazon/this-week-in-neovim-contents#268]
Hello!

The license for Hop seems to be a BSD license, not a BDS one :) I don't know how common it is, but I like using the SPDX identifiers for licenses, so it seems [`BSD-3-Clause`](https://spdx.org/licenses/BSD-3-Clause.html) would be the way to go, but I don't really know if there's an official source for license naming.

Have fun :D

**Comment by phaazon** [comment]
You’re right, thanks, I’ll fix that!
