### ISSUE TITLE
Unable to open website

### ISSUE THREAD

**Issue by radvil** [phaazon/this-week-in-neovim-contents#281]
![image](https://github.com/phaazon/this-week-in-neovim-contents/assets/36059968/8d095854-24fd-4f6d-b13b-5b8b59af28c4)

**Comment by miversen33** [comment]
It was announced several months ago that they were phasing this project out as they were no longer interested in managing it. I can find the reddit post with details on it if needed.

Note, there is an effort to transfer TWIN to [dotfyle](https://dotfyle.com/), see [here](https://www.reddit.com/r/neovim/comments/14mukmv/this_week_in_neovim_current_status_future_etc/) for details.

@phaazon would you accept a PR or pin an issue stating this project is no longer active, and maybe some details on where its new home will be? That seems like a reasonable way to finish out this project :)

**Comment by phaazon** [comment]
Sure I would!
