### ISSUE TITLE
Add (sub)section with present issue contributors

### ISSUE THREAD

**Issue by echasnovski** [phaazon/this-week-in-neovim-contents#38]
It might be nicer and more rewarding contribution experience for people if they know their efforts will be recognized in the newsletter itself.

Maybe in updated version of currently present "Want to contribute?" section? It can be a list of Github links to those who made a present issue contribution (with a possible lead-in "They have already contributed to this week's issue"). Also updated contribution guidelines to invite users to add themselves to the list.

**Comment by phaazon** [comment]
Yeah, that can be great idea!

**Comment by phaazon** [comment]
I’ve been doing that for two releases now!
