### ISSUE TITLE
Rename folders

### ISSUE THREAD

**Issue by EpsilonKu** [phaazon/this-week-in-neovim-contents#83]
What about to rename month folders to `NN-MMM` format (example: 10-Oct). It's easy navigate when folders on order.

**Comment by phaazon** [comment]
Yeah, that could work, but that would mean changing the backend to be able to read those folders correctly and I don’t really have time to do that. If someone wants to come up with a PR, it’s more than welcome [here](https://github.com/phaazon/this-week-in-neovim.org).
