### ISSUE TITLE
Email subscription

### ISSUE THREAD

**Issue by muhammad-saleh** [phaazon/this-week-in-neovim-contents#87]
Thank you for the amazing newsletter.
I was wondering if there's a way to subscribe to this through an email and not RSS?

**Comment by towry** [comment]
Miss google reader.

**Comment by phaazon** [comment]
There won’t be email subscription as:

1. I don’t want to be held responsible for keeping emails safe.
2. I hate the technology and would prefer promoting feed like RSS.

**Comment by stsewd** [comment]
Another option could be to have a meta issue on GitHub, similar to https://github.com/neovim/neovim/issues/14090, so users can subscribe, and receive notifications every time a new issue is released
