### ISSUE TITLE
Please consider Creative Commons license

### ISSUE THREAD

**Issue by HiPhish** [phaazon/this-week-in-neovim-contents#9]
The newsletter is using the 3-clause BSD license, but that license is intended four source code. It talks about warranty and binary form, which are concepts that don't really make sense for prose text. A [Creative Commons](https://creativecommons.org/) license would be more appropriate for a newsletter (I propose `CC BY` or `CC BY SA` if you want to be more restrictive). Even the FSF [recommends](https://www.gnu.org/licenses/license-list.html#OtherLicenses) the CC licenses (among others) for non-software.

I say this now because the more contributors you have, the harder it will be to change the license after the fact. You would need every contributor to agree with re-licensing their work.

**Comment by phaazon** [comment]
Agreed, good point. I will switch the license. However, what is under BSD-3 is the actual source code of the website. The content is not really licensed right now.

Any idea how to make the distinction?

**Comment by HiPhish** [comment]
> Any idea how to make the distinction?

I think inserting a license notice somewhere in the *produced* website should be enough, that is how Wikipedia for example does it. The code of the website is of course actual source code, so it makes sense to have it BSD-licensed. Since the website source and the website content are already different repositories you can just put a different `LICENSE` file in each of them.

**Comment by phaazon** [comment]
Alright, that should be enough. I might at some point include the actual license text instead of redirecting to the source repository, but I think it’s okay for now. Thanks for raising the concern @HiPhish!
