### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by lucax88x** [phaazon/this-week-in-neovim-contents#92]
Ciao! 

What about some donation form whatsoever? Like neovim by GitHub.

Thanks for your work!

**Comment by phaazon** [comment]
I need to set it up and I’m not sure what I need to do in terms of legal thing. Not sure whether I have to declare a special status or such.

**Comment by phaazon** [comment]
Also, I’m going to close and leave #14 open as it’s overlapping. Thanks again!
